### PR TITLE
Expose tickSize and tickValues from within d3fc-charts

### PR DESCRIPTION
**Pull request by rcassonScottLogic**
exposes tickSize and tickValues for any d3fc-axis from within d3fc-charts

also updates an example to show code in use and updated the README to reflect changes

### CODE REVIEW

**Comment by rcassonScottLogic** [comment]
@ryanggrey can you review this please?

**Comment by chrisprice** [comment]
@rcassonScottLogic it might be worth using `d3fc-rebase` to expose methods from nested components. I'm a bit confused as to why we didn't do this for `x/yTicks` but I think that might be due to a timing issue (@colineberhardt).

**Comment by rcassonScottLogic** [comment]
did you mean `d3fc-rebind`? if not i cant seem to find `d3fc-rebase`

**Comment by chrisprice** [comment]
My bad, that's the one.

**Comment by rcassonScottLogic** [comment]
would it be worth rebinding all the properties from `d3fc-axis` to `d3fc-chart`? or atleast just `x/ytick Format, Args, Size, Values and Decorate`

**Comment by rcassonScottLogic** [comment]
since `d3fc-axis` needs to be created with an orientation, which can be configured, and the axis isn't created until the render method is called. i cant directly hook into the axis object to expose the properties within until the axis is being rendered, which will be too late to allow configuration. 

so i guess the `x/yTicks` is handled is the correct way?

**Comment by ColinEberhardt** [comment]
Thanks @rcassonScottLogic this all looks good to me. Although, I think the 'spirit' of the issue #20 is that all the underlying tick properties should be exposed.

Looking at the docs (https://github.com/d3/d3-axis), I `tickSizeInner`, `tickSizeOuter`, `tickArguments` and `tickPadding` should also be added.

From a brief inspection of d3fc-axis, it looks like we support all of these properties.

**Comment by ColinEberhardt** [comment]
Thanks for the updates @rcassonScottLogic - one final thing, properties should have the following form:

```
        cartesian.xDecorate = (...args) => {
            if (!args.length) {
                return xDecorate;
            }
            xDecorate = args[0];
            return cartesian;
        };
```

This allows you to both use them as setters, `chart.xDecorate(val)` and getters, `chart.xDecorate()` - this is a standard D3 pattern.

The only exception is the occasional 'special' property that simply captures the arguments it is invoked with, these do not have getters.

Basically, you've picked the wrong pattern to copy ;-)

**Comment by ColinEberhardt** [comment]
Thanks @rcassonScottLogic

**Pull request merged**
